# Generated by Django 4.2.7 on 2023-12-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_genre', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
