# Generated by Django 4.2.7 on 2023-11-08 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_mebel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['parse_datetime', '-price'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AddField(
            model_name='mebel',
            name='parse_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата прихода к нам'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mebel',
            name='description',
            field=models.TextField(verbose_name='Описание с куфара'),
        ),
        migrations.AlterField(
            model_name='mebel',
            name='link',
            field=models.TextField(verbose_name='Ссылка'),
        ),
    ]
